## Множественная линейная регрессия с sklearn

#### Импорт библиотек

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression as LR

#### Загрузка данных

In [2]:
data = pd.read_csv('1.02. Multiple linear regression1.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

#### Объявляем зав/незав переменные

In [4]:
x = data [['SAT','Rand 1,2,3']]
y = data ["GPA"]

In [5]:
reg= LR()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

### GPA =0.296 + 0.00165 * 'SAT' - 0.0083 * 'Rand 1,2,3'

#### R-квадрат

In [8]:
round(reg.score(x,y),3)

0.407

####  Скорректированный R-квадрат
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [9]:
x.shape

(84, 2)

In [10]:
R_adj = 1 - (1-reg.score(x,y)) * (x.shape[0]-1)/(x.shape[0]-x.shape[1]-1)
round(R_adj,3)

0.392

 #### Определнеие несущественной независимой переменной

In [11]:
from sklearn.feature_selection import f_regression

In [12]:
f_regression (x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

Первый массив - f-статистика, второй - p-value

In [13]:
f_stat = f_regression (x,y)[0]
f_stat

array([56.04804786,  0.17558437])

In [14]:
p_val = f_regression (x,y)[1]
p_val

array([7.19951844e-11, 6.76291372e-01])

In [15]:
p_val.round(3)

array([0.   , 0.676])

Так как p-value второй переменной (Rand 1,2,3) > 0.05, то мы определяем её как бесполезную переменную. И она должна быть убрана из модели

#### Создаем отчет

In [16]:
reg_summ = pd.DataFrame(data = x.columns.values, columns = ['Feachures'])
reg_summ

Feachures
0         SAT
1  Rand 1,2,3

In [17]:
reg_summ ['Coefficients'] = reg.coef_
reg_summ ['p-values'] = p_val.round(3)

In [18]:
reg_summ

Feachures  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676