# Why NumPy?

In [1]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [12]:
array_hw_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array_hw_1

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2.Check its type, shape and size. 
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [13]:
type(array_hw_1)

numpy.ndarray

In [14]:
array_hw_1.shape

(8,)

In [15]:
array_hw_1.size

8

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen. 

In [18]:
array_hw_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 4. Find its type, shape, and size. 

In [19]:
array_hw_2.shape

(2, 4)

In [20]:
array_hw_2.size

8

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_2 </i> and display it on screen.

In [23]:
array_hw_3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(array_hw_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### 6. Find its type, shape and size. 


In [24]:
array_hw_3.shape

(1, 3, 3)

In [25]:
array_hw_3.size

9

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [26]:
list_hw_1 = [[1, 2, 3, 4], [5, 6, 7, 8]]

### 8. Find the length of this 2-D list. 

In [27]:
len(list_hw_1)

2

### 9. Fint the length of one of its sublists. 

In [28]:
len(list_hw_1[0])

4

### 10. Verify its type. 

In [29]:
type(list_hw_1)

list

### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [31]:
a = np.array(list_hw_1)

In [32]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [33]:
b = list_hw_1 + list_hw_1

In [35]:
c = a + a

In [36]:
b

[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [5, 6, 7, 8]]

In [37]:
c

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [38]:
np.sqrt(c)

array([[1.41421356, 2.        , 2.44948974, 2.82842712],
       [3.16227766, 3.46410162, 3.74165739, 4.        ]])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [39]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])